name: 'Azure Compliance Checker'
description: 'Azure Compliance Testing Action using Chef Inspec, Dev-Sec and Inspec-Azure'
branding:
  icon: 'alert-triangle'
  color: 'orange'
inputs:
  subscriptionId: 
    description: 'Azure Subscription ID'
    required: true
  clientId:
    description: 'Azure Client ID'
    required: true
  clientSecret:
    description: 'Azure Client Secret'
    required: true
  tenantId:
    description: 'Azure Tenant ID'
    required: true
  compliance_test_profile_url:
    description: 'Compliance test file url'
    required: false
runs: 
  using: "composite"

  steps:
    - run: echo "azure_compliance_action execution started"
      shell: bash   

    - run: ${{ github.action_path }}/app/index.sh  
      shell: bash
      env:
        INPUT_ACTION_PATH: ${{ github.action_path }}
        INPUT_SUBSCRIPTIONID: ${{ inputs.subscriptionId }}
        INPUT_CLIENTID: ${{ inputs.clientId }}
        INPUT_TENANTID: ${{ inputs.tenantId }}
        INPUT_CLIENTSECRET: ${{ inputs.clientSecret }}
        INPUT_COMPLIANCE_TEST_PROFILE_URL: ${{ inputs.compliance_test_profile_url }}

    - run: echo  "azure_compliance_action execution completed"
      shell: bash   


      