name: 'Azure Compliance Checker'
description: 'Azure Compliance Testing Action using Chef Inspec, Dev-Sec and Inspec-Azure'
branding:
  icon: 'alert-triangle'
  color: 'gray-dark'
inputs:
  subscriptionId: 
    description: 'Azure Subscription ID'
    required: true
  clientId:
    description: 'Azure Client ID'
    required: true
  clientSecret:
    description: 'Azure Client Secret'
    required: true
  tenantId:
    description: 'Azure Tenant ID'
    required: true
runs: 
  using: "composite"

  steps:
    - run: echo Hello Started.
      shell: bash   
    
    - run: ${{ github.action_path }}/app/index.sh ${{ github.action_path }}
      shell: bash
      env:
        subscription_id: ${{ inputs.subscriptionId }}
        client_id: ${{ inputs.clientId }}
        client_secret: ${{ inputs.clientSecret }} 
        tenant_id: ${{ inputs.tenantId }}

      