name: 'Azure Compliance Checker'
description: 'Azure Compliance Testing Action using Chef Inspec, Dev-Sec and Inspec-Azure'
branding:
  icon: 'alert-triangle'
  color: 'gray-dark'
inputs:
  subscriptionId: 
    description: 'Azure Subscription ID'
    required: true
  clientId:
    description: 'Azure Client ID'
    required: true
  clientSecret:
    description: 'Azure Client Secret'
    required: true
  tenantId:
    description: 'Azure Tenant ID'
    required: true
runs: 
  using: "composite"

  steps:
    - run: echo Started.
      shell: bash   

    - run: ${{ github.action_path }}/app/index.sh ${{ github.action_path }} ${{ inputs.subscriptionId }} ${{ inputs.clientId }} ${{ inputs.tenantId }} ${{ inputs.clientSecret }}
      shell: bash

     - run: echo Completed.
      shell: bash   


      