name: 'Azure Compliance Checker'
description: 'Azure Compliance Testing Action using Chef Inspec, Dev-Sec and Inspec-Azure'
branding:
  icon: 'alert-triangle'
  color: 'gray-dark'
inputs:
  subscriptionId: 
    description: 'Azure Subscription ID'
    required: true
  clientId:
    description: 'Azure Client ID'
    required: true
  clientSecret:
    description: 'Azure Client Secret'
    required: true
  tenantId:
    description: 'Azure Tenant ID'
    required: true
runs: 
  using: "composite"

  steps:
    - run: echo Hello Started.
      shell: bash   

    - name: Environment setting
      shell: bash
      run: |
        export subscription_id=${{ inputs.subscriptionId }}
        export client_id=${{ inputs.client_id }}
        export client_secret=${{ inputs.client_secret }}
        export tenant_id=${{ inputs.tenant_id }}
        echo completed
      
    - run: ${{ github.action_path }}/app/index.sh ${{ github.action_path }} ${{ inputs.subscriptionId }} ${{ inputs.clientId }} ${{ inputs.clientSecret }} ${{ inputs.tenantId }}
      shell: bash

      