name: 'Azure Compliance Checker'
description: 'Azure Compliance Testing Action using Chef Inspec, Dev-Sec and Inspec-Azure'
branding:
  icon: 'alert-triangle'
  color: 'gray-dark'
inputs:
  Azure_subscriptionId: 
    description: 'Azure Subscription ID'
    required: true
  Azure_clientId:
    description: 'Azure Client ID'
    required: true
  Azure_clientSecret:
    description: 'Azure Client Secret'
    required: true
  Azure_tenantId:
    description: 'Azure Tenant ID'
    required: true
runs: 
  using: "composite"

  steps:
    - run: echo Hello Started.
      shell: bash   
    - name: Inspection of Azure
      shell: bash
      run: |
        echo "Good started"
        curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec 
        cp -r ${{ github.action_path }}/inspec-azure-check-profile .

        export subscription_id= ${{ inputs.Azure_subscriptionId }}
        export client_id=${{ inputs.Azure_clientId }}
        export client_secret=${{ inputs.Azure_clientSecret }} 
        export tenant_id=${{ inputs.Azure_tenantId }}

        inspec check inspec-azure-check-profile --chef-license accept-silent
        inspec exec inspec-azure-check-profile -t azure:// --reporter cli junit:testresults.xml html:report.html --chef-license accept-silent
        
        echo "Completed"