name: 'Azure Compliance Checker'
description: 'Azure Compliance Testing Action using Chef Inspec, Dev-Sec and Inspec-Azure'
branding:
  icon: 'alert-triangle'
  color: 'gray-dark'
inputs:
  subscriptionId: 
    description: 'Azure Subscription ID'
    required: true
  clientId:
    description: 'Azure Client ID'
    required: true
  clientSecret:
    description: 'Azure Client Secret'
    required: true
  tenantId:
    description: 'Azure Tenant ID'
    required: true
runs: 
  using: "composite"

  steps:
    - run: echo Hello Started.
      shell: bash   

    - name: Environment setting
      shell: bash
      run: |       
        export AZURE_SUBSCRIPTION_ID=${{ inputs.subscriptionId }}
        export AZURE_CLIENT_ID=${{ inputs.clientId }}
        export AZURE_TENANT_ID=${{ inputs.tenantId }}
        export AZURE_CLIENT_SECRET=${{ inputs.clientSecret }}

        echo completed
      
    - run: ${{ github.action_path }}/app/index.sh ${{ github.action_path }} 
      shell: bash

      