name: 'Azure Compliance Checker'
description: 'Azure Compliance Testing Action using Chef Inspec, Dev-Sec and Inspec-Azure'
branding:
  icon: 'alert-triangle'
  color: 'gray-dark'
inputs:
  Azure_subscriptionId: 
    description: 'Azure Subscription ID'
    required: true
  Azure_clientId:
    description: 'Azure Client ID'
    required: true
  Azure_clientSecret:
    description: 'Azure Client Secret'
    required: true
  Azure_tenantId:
    description: 'Azure Tenant ID'
    required: true
runs: 
  using: "composite"

  steps:
    - run: echo Hello Started.
      shell: bash   
    - run: ${{ github.action_path }}/app/index.sh ${{ github.action_path }} ${{ inputs.Azure_subscriptionId }} ${{ inputs.Azure_clientId }} ${{ inputs.Azure_clientSecret }} ${{ inputs.Azure_tenantId }}
      shell: bash