name: 'Azure Compliance Checker'
description: 'Azure Compliance Testing Action using Chef Inspec, Dev-Sec and Inspec-Azure'
branding:
  icon: 'alert-triangle'
  color: 'gray-dark'
inputs:
  subscriptionId: 
    description: 'Azure Subscription ID'
    required: true
  clientId:
    description: 'Azure Client ID'
    required: true
  clientSecret:
    description: 'Azure Client Secret'
    required: true
  tenantId:
    description: 'Azure Tenant ID'
    required: true
runs: 
  using: "composite"

  steps:
    - run: echo Hello Started.
      shell: bash   
    - name: Inspection of Azure
      shell: bash
      run: |
        echo "Good started"
        curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec 
        cp -r ${{ github.action_path }}/inspec-azure-check-profile .

        echo $INPUTS_SUBSCRIPTIONID
        echo "$INPUTS_SUBSCRIPTIONID"
        echo "$inputs.Azure_subscriptionId"
        echo "$Azure_subscriptionId"

        export subscription_id= "$INPUTS_SUBSCRIPTIONID"
        export client_id=${{ inputs.clientId }}
        export client_secret=${{ inputs.clientSecret }} 
        export tenant_id=${{ inputs.tenantId }}

        inspec check inspec-azure-check-profile --chef-license accept-silent
        inspec exec inspec-azure-check-profile -t azure:// --reporter cli junit:testresults.xml html:report.html --chef-license accept-silent
        
        echo "Completed"